#!/bin/sh
docker run \
--name ocs \
-e TEST="test"  \
-e DB_USER="ocsusr" \
-e DB_PASS="Ocsp455" \
-e DB_NAME="ocsweb" \
-e MYSQL_ROOT_PASSWORD="N4mtudom1!" \
--link apia-mariadb:db \
-p 8081:80 \
-d eddie303/ocsinventory-ng
